name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake
        choco install mingw

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake
        brew install llvm

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Run benchmarks
      run: |
        cd build
        ./bin/RoadConstructionTests --gtest_filter="*Benchmark*"

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake cppcheck

    - name: Static analysis
      run: |
        cppcheck --enable=all --std=c++17 --language=c++ src/ include/ --error-exitcode=1

    - name: Check formatting
      run: |
        # Add clang-format check here if needed
        echo "Format check passed"

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check documentation
      run: |
        # Check if README exists and has content
        if [ ! -s README.md ]; then
          echo "README.md is missing or empty"
          exit 1
        fi
        
        # Check if test plan exists
        if [ ! -s test_plan.md ]; then
          echo "test_plan.md is missing or empty"
          exit 1
        fi

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Security scan
      run: |
        # Add security scanning tools here
        echo "Security scan completed"

  deploy:
    needs: [build-and-test, code-quality, documentation, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build release
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Create release artifacts
      run: |
        mkdir -p release
        cp build/bin/RoadConstruction release/
        cp README.md release/
        cp test_plan.md release/
        tar -czf road-construction-v1.0.0.tar.gz release/

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: road-construction-release
        path: road-construction-v1.0.0.tar.gz 